<a href="https://colab.research.google.com/github/SwamptoForest/exp/blob/main/gyocha.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import sklearn
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3, random_state=1)
dt_clf = DecisionTreeClassifier(random_state =1)
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
round(accuracy_score(y_test, pred), 4)

0.9556

In [ ]:
from sklearn.model_selection import KFold
kfold = KFold(n_splits=5)

iris = load_iris()
feature = iris.data
label = iris.target

cv_accuracy = []
n_iter =0
dt_clf = DecisionTreeClassifier(random_state=1)

In [ ]:
feature.shape

(150, 4)

In [ ]:
n_iter =0
for train_index, test_index in kfold.split(feature):
  x_train, x_test = feature[train_index], feature[test_index]
  y_train, y_test = label[train_index], label[test_index]

  dt_clf.fit(x_train, y_train)
  pred = dt_clf.predict(x_test)
  n_iter += 1

  accuracy = np.round(accuracy_score(y_test, pred), 4)
  train_size = x_train.shape[0]
  test_size = x_test.shape[0]

  print('\n#{0} 교차 검증 정확도:{1}, 학습 데이터 크기 :{2}, 검증 데이터 크기 :{3}'
    .format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))
  cv_accuracy.append(accuracy)

#1 교차 검증 정확도:1.0, 학습 데이터 크기 :120, 검증 데이터 크기 :30
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도:1.0, 학습 데이터 크기 :120, 검증 데이터 크기 :30
#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도:0.9, 학습 데이터 크기 :120, 검증 데이터 크기 :30
#3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도:0.9333, 학습 데이터 크기 :120, 검증 데이터 크기 :30
#4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도:0.7333, 학습 데이터 크기 :120, 검증 데이터 크기 :30
#5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

In [ ]:
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))

## 평균 검증 정확도: 0.91332

In [ ]:
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [ ]:
kfold_1= KFold(n_splits=3)
n_iter_= 0

for train_index, test_index in kfold_1.split(iris_df):
  n_iter_+=1
  train = iris_df['label'].iloc[train_index]
  test = iris_df['label'].iloc[test_index]

  print('# 교차 검증:{}'.format(n_iter_))
  print('# 학습 레이블 데이터 : \n',train.value_counts())
  print('# 검증 레이블 데이터 : \n',test.value_counts())

# 교차 검증:1
# 학습 레이블 데이터 :
 label
1    50
2    50
Name: count, dtype: int64
# 검증 레이블 데이터 :
 label
0    50
Name: count, dtype: int64
# 교차 검증:2
# 학습 레이블 데이터 :
 label
0    50
2    50
Name: count, dtype: int64
# 검증 레이블 데이터 :
 label
1    50
Name: count, dtype: int64
# 교차 검증:3
# 학습 레이블 데이터 :
 label
0    50
1    50
Name: count, dtype: int64
# 검증 레이블 데이터 :
 label
2    50
Name: count, dtype: int64

In [ ]:
kfold = KFold(n_splits=3)
n_iter =0
for train_index, test_index in kfold.split(feature):
  x_train, x_test = feature[train_index], feature[test_index]
  y_train, y_test = label[train_index], label[test_index]

  dt_clf.fit(x_train, y_train)
  pred = dt_clf.predict(x_test)
  n_iter += 1

  accuracy = np.round(accuracy_score(y_test, pred), 4)
  train_size = x_train.shape[0]
  test_size = x_test.shape[0]

  print('\n#{0} 교차 검증 정확도:{1}, 학습 데이터 크기 :{2}, 검증 데이터 크기 : {3}'
    .format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스 : {1}'.format(n_iter,test_index))
  cv_accuracy.append(accuracy)

#1 교차 검증 정확도:0.0, 학습 데이터 크기 :100, 검증 데이터 크기 : 50
#1 검증 세트 인덱스 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]

#2 교차 검증 정확도:0.0, 학습 데이터 크기 :100, 검증 데이터 크기 : 50
#2 검증 세트 인덱스 : [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]

#3 교차 검증 정확도:0.0, 학습 데이터 크기 :100, 검증 데이터 크기 : 50
#3 검증 세트 인덱스 : [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

# 위처럼 결과가 나오는 경우에 일반 k-Fold 교차 검증이 아닌 계층별 교차 검증이 더 좋은 방식이다. 위와 같이 편식으로 발생하는 결과가 나오지않도록 강제로 비율을 맞춰서 골고루 먹게하는 방식이기 때문이다.
그래서 다음으로 나오는게 계층별 교차 검증(Stratified Kfold)이다.

In [ ]:
from sklearn.model_selection import StratifiedKFold

S_kfold = StratifiedKFold(n_splits=5)

cv_accuracy = []
n_iter =0

for train_index, test_index in S_kfold.split(feature, label):
  x_train, x_test = feature[train_index], feature[test_index]
  y_train, y_test = label[train_index], label[test_index]

  dt_clf.fit(x_train, y_train)
  pred = dt_clf.predict(x_test)
  n_iter += 1

  accuracy = np.round(accuracy_score(y_test, pred), 4)
  train_size = x_train.shape[0]
  test_size = x_test.shape[0]

  print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기 :{2}, 검증 데이터 크기 : {3}'
    .format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스 : {1}'.format(n_iter,test_index))
  cv_accuracy.append(accuracy)

print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))

#1 교차 검증 정확도 :0.9667, 학습 데이터 크기 :120, 검증 데이터 크기 : 30
#1 검증 세트 인덱스 : [  0   1   2   3   4   5   6   7   8   9  50  51  52  53  54  55  56  57
  58  59 100 101 102 103 104 105 106 107 108 109]

#2 교차 검증 정확도 :0.9667, 학습 데이터 크기 :120, 검증 데이터 크기 : 30
#2 검증 세트 인덱스 : [ 10  11  12  13  14  15  16  17  18  19  60  61  62  63  64  65  66  67
  68  69 110 111 112 113 114 115 116 117 118 119]

#3 교차 검증 정확도 :0.9, 학습 데이터 크기 :120, 검증 데이터 크기 : 30
#3 검증 세트 인덱스 : [ 20  21  22  23  24  25  26  27  28  29  70  71  72  73  74  75  76  77
  78  79 120 121 122 123 124 125 126 127 128 129]

#4 교차 검증 정확도 :1.0, 학습 데이터 크기 :120, 검증 데이터 크기 : 30
#4 검증 세트 인덱스 : [ 30  31  32  33  34  35  36  37  38  39  80  81  82  83  84  85  86  87
  88  89 130 131 132 133 134 135 136 137 138 139]

#5 교차 검증 정확도 :1.0, 학습 데이터 크기 :120, 검증 데이터 크기 : 30
#5 검증 세트 인덱스 : [ 40  41  42  43  44  45  46  47  48  49  90  91  92  93  94  95  96  97
  98  99 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.96668

In [ ]:
iris_df['label'].value_counts()

label
0    50
1    50
2    50
Name: count, dtype: int64

In [ ]:
skfold_1 = StratifiedKFold(n_splits=5)
n_iter_= 0

for train_index, test_index in skfold_1.split(iris_df, iris_df['label']):
  n_iter_+=1
  train = iris_df['label'].iloc[train_index]
  test = iris_df['label'].iloc[test_index]

  print('# 교차 검증:{}'.format(n_iter_))
  print('# 학습 레이블 데이터 : \n',train.value_counts())
  print('# 검증 레이블 데이터 : \n',test.value_counts())

# 교차 검증:1
# 학습 레이블 데이터 :
 label
0    40
1    40
2    40
Name: count, dtype: int64
# 검증 레이블 데이터 :
 label
0    10
1    10
2    10
Name: count, dtype: int64
# 교차 검증:2
# 학습 레이블 데이터 :
 label
0    40
1    40
2    40
Name: count, dtype: int64
# 검증 레이블 데이터 :
 label
0    10
1    10
2    10
Name: count, dtype: int64
# 교차 검증:3
# 학습 레이블 데이터 :
 label
0    40
1    40
2    40
Name: count, dtype: int64
# 검증 레이블 데이터 :
 label
0    10
1    10
2    10
Name: count, dtype: int64
# 교차 검증:4
# 학습 레이블 데이터 :
 label
0    40
1    40
2    40
Name: count, dtype: int64
# 검증 레이블 데이터 :
 label
0    10
1    10
2    10
Name: count, dtype: int64
# 교차 검증:5
# 학습 레이블 데이터 :
 label
0    40
1    40
2    40
Name: count, dtype: int64
# 검증 레이블 데이터 :
 label
0    10
1    10
2    10
Name: count, dtype: int64

In [4]:
import sklearn
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

from sklearn.model_selection import cross_val_score

iris = load_iris()
feature = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=1)

basic_scores = cross_val_score(dt_clf, feature, label)
print('\n##cross_val_score를 통한 성능 평가 :', basic_scores)

##cross_val_score를 통한 성능 평가 : [0.96666667 0.96666667 0.9        1.         1.        ]

------------- L O O C V ----------------------

K-Fold 와 비교했을 때 데이터 학습의 일관성 유지에 좋은 방식이라고 한다. 결과적으로 모델의 평균적인 일반화 성능을 가장 꼼꼼하게 채점할 수 있다.

In [5]:
from sklearn.model_selection import LeaveOneOut

iris = load_iris()
feature = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=1)

loocv = LeaveOneOut()
score = cross_val_score(dt_clf, feature, label, cv = loocv)

print("\n## 교차 검증 횟수 :", len(score))
print('\n## 평균 검증 정확도:', round(np.mean(score),4))

## 교차 검증 횟수 : 150

## 평균 검증 정확도: 0.94

------------- 반복 / 그룹별 교차 검증 ----------------------

데이터 학습에서 불확실성을 최대한 줄이고자 섞고 분할해서 평가하는 사이클을 반복하는 것이 반복 교차 검증이고 그룹별 교차 검증은 데이터 안의 특정 그룹이 있다면 그 데이터를 train과 test로 나뉘게 하지않고 그룹 통째로 어느 한쪽으로 들어가게 하는 것인데 그렇게 하는 이유는 특정 그룹이 학습에도 쓰이고 시험에도 쓰이면 그 특정 그룹에 대한 과적합이 일어날 수 있기 때문에 방지하고자 함이다.

In [6]:
from sklearn.model_selection import RepeatedStratifiedKFold

iris = load_iris()
feature = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=1)

rskfold = RepeatedStratifiedKFold()
score = cross_val_score(dt_clf, feature, label, cv = rskfold)

print("\n## 교차 검증 횟수 :", len(score))
print('\n## 평균 검증 정확도:', round(np.mean(score),4))

## 교차 검증 횟수 : 50

## 평균 검증 정확도: 0.9473